name: 2025-book-env
channels:
- conda-forge
- pytorch
- defaults
dependencies:
- python=3.11 
- nb_conda_kernels
- ipykernel         
- numpy 
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- notebook >=7.0
- ipywidgets
- nbdime
- emcee
- ptemcee
- zeus-mcmc
- numdifftools
- corner
- scikit-learn
- scikit-image
- pydoe
- pytorch
- torchvision
- jupyter-book=1.0.*
- sphinx=7.4.*
- myst-parser=3.0.*
- myst-nb=1.3.*
- pydata-sphinx-theme=0.15.*
- sphinx-book-theme=1.1.*
- nbclient=0.10.*
- ghp-import
- arviz
- panel
- bokeh
- pymc >=5.0
- pip
- pip:
  - prettyplease
  - sphinx-proof
  - sphinx-inline-tabs
  - sphinx-exercise
  - gpy
  - gpyopt  
  - pymultinest
  - pocomc


