name: 2025-env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11.*
  - nb_conda_kernels=2.5.*
  - numpy=1.26.*
  - scipy=1.16.*
  - matplotlib=3.10.*
  - pandas=2.3.*
  - seaborn=0.13.*
  - jupyter=1.1.*
  - notebook >=7.0
  - ipykernel=7.1.*         
  - ipywidgets=8.1.*
  - nbdime=4.0.*
  - arviz=0.22.*
  - emcee=3.1.*
  - ptemcee=1.0.*
  - zeus-mcmc=2.5.*
  - numdifftools=0.9.*
  - corner=2.2.*
  - scikit-learn=1.7.*
  - scikit-image=0.25.*
  - pydoe=0.3.*
  - pytorch=2.8.*
  - torchvision=0.24.*
  - panel=1.8.*
  - bokeh=3.8.*
  - pip=25.*
  - pip:
       - watermark==2.5.0
       - pocomc==1.2.6
